name: sentry_dart_plugin
version: 1.1.0
description: >
  A Dart Build Plugin that uploads symbols for Android, iOS/macOS, and Web to Sentry via sentry-cli.
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart-plugin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yaml: ^3.1.0
  injector: ^2.0.0
  ansicolor: ^2.0.1
  system_info2: ^3.0.1
  file: ^6.1.4
  http: ^0.13.5
  crypto: ^3.0.2
  convert: ^3.0.2
  process: ^4.2.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
