name: sentry_dart_plugin
version: 2.1.0
description: Uploads debug symbols to Sentry for server-side symbolication.
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart-plugin

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  yaml: ^3.1.0
  injector: ^3.0.0
  ansicolor: ^2.0.1
  system_info2: '>=3.0.1 <5.0.0'
  file: '>=6.1.4 <8.0.0'
  http: '>=0.13.0 <2.0.0'
  crypto: ^3.0.2
  convert: ^3.0.2
  process: '>=4.2.4 <6.0.0'
  properties: ^2.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.6

platforms:
  linux:
  windows:
  macos:
