name: 'Sentry Dart Plugin'
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
jobs:
  build:
    name: 'Analyze, Format and Build'
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta]

    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - uses: actions/checkout@v3.5.0

      - name: 'Pub Get'
        run: |
          dart pub get

      - name: 'Analyze and Format'
        run: |
          dart analyze --fatal-infos
          dart format --set-exit-if-changed ./

      - run: dart test

      - name: Build
        run: |
          dart compile aot-snapshot bin/sentry_dart_plugin.dart

  package-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      # - name: "Check scores"
      #   env:
      #     TOTAL: ${{ steps.analysis.outputs.total }}
      #     TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
      #   run: |
      #     PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
      #     if (( $PERCENTAGE < 100 ))
      #     then
      #       echo Score too low!
      #       exit 1
      #     fi
