name: integration-tests-sentry-cli

on:
  push:
    branches:
      -master
  pull_request:

defaults:
  run:
    working-directory: integration-test/project

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest] # TODO: add linux & windows
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download sentry-cli binaries
        run: ../../scripts/download-sentry-cli.sh

      - name: flutter pub get
        run: |
          flutter clean
          flutter pub get

      - name: Build apk
        run: flutter build apk
            
      - name: Start server and run integration tests
        run: |
          ../integration-test-server-start.sh &
          dart lib/plugin.dart
