name: integration-tests-sentry-cli

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

defaults:
  run:
    working-directory: integration-test

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macos, ubuntu, windows]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 #2.16.0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - run: flutter pub get

      - run: flutter build apk
        
      - run: flutter build ipa --no-codesign
        if: matrix.os == 'macos'

      - run: flutter build macos --no-codesign
        if: matrix.os == 'macos'

      - run: flutter build web --source-maps

      - run: scripts/test.ps1
        shell: pwsh
