name: integration-tests-sentry-cli

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

defaults:
  run:
    working-directory: integration-test

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macos, ubuntu, windows]
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa #2.10.0
        with:
          flutter-version: '3.13.2'
          channel: 'stable'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - run: flutter pub get

      - run: flutter build apk
        
      - run: flutter build ipa --no-codesign
        if: matrix.os == 'macos'

      - run: flutter build web --source-maps

      - run: scripts/test.ps1
        shell: pwsh
