name: integration-tests-sentry-cli

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: integration-test

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macos, ubuntu, windows]
    steps:
      - uses: actions/checkout@v3.5.2

      - uses: subosito/flutter-action@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - run: flutter pub get

      - run: flutter build apk

      - run: flutter build web --source-maps

      - run: scripts/test.ps1
        shell: pwsh
